### PR TITLE
Remove sdm845-userdebug build target

### PR DESCRIPTION
**Pull request by pundiramit**
Remove the common sdm845-userdebug build target.
Move the common device configs to device-common.mk and
{beryllium,enchilada}/device.mk file.

Signed-off-by: Amit Pundir <amit.pundir@linaro.org>

### CODE REVIEW

**Comment by pundiramit** [comment]
@calebccff @amartinz Smoke tested on beryllium. Build tested for enchilada.

**Comment by calebccff** [comment]
This looks good to me, I'll test it out tomorrow. What's the right order to merge this and #5?

**Comment by amartinz** [comment]
Thank you, will test tomorrow as well!

> This looks good to me, I'll test it out tomorrow. What's the right order to merge this and #5?

i'll rebase #5 on it :)
So this should go in before #5.

**Comment by amartinz** [comment]
Works for axolotl.

Did not test beryllium or enchilada.

**Pull request merged**
